esphome:
  name: pc-power
  platform: ESP8266 # ESP8266 or ESP32
  board: nodemcuv2  # Any ESP8266 or ESP32 board

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PC Power  Fallback Hotspot"
    password: !secret esphome_ap_password

# Enable logging
logger:

api:
  password: !secret esphome_api_password
ota:
  password: !secret esphome_ota_password

switch:
  - platform: gpio
    name: "PC Power button"
    icon: "mdi:electric-switch"
    pin: D2   # Power button output pin
    inverted: no
    id: power_pin
binary_sensor:
  - platform: gpio
    pin: D1   # Power detect input pin
    name: "PC Power Sense"
    device_class: power
